### ISSUE TITLE
Many instances of `remote error: tls: bad record MAC` errors in the logs when uploading

### ISSUE THREAD

**Issue by anoadragon453** [simulot/immich-go#113]
While attempting to upload photos from my Google takeout, I see the following error for about 1 in every 20 photos:

```
Server error             : Takeout/Google Photos/Photos from 2014/IMG_5170.JPG: AssetUpload, POST, https://i.amorgan.xyz/api/asset/upload
Post "https://i.amorgan.xyz/api/asset/upload": remote error: tls: bad record MAC
```

This is annoying as it appears that these photos are just being left behind during the upload. I'll have to note down which photos failed and try them again, repeating the process until there are no errors left.

On my immich microservices container, I am seeing the following error regularly appear:

```
Dec 30 22:05:37 plonkie docker-immich_microservices-start[1341286]: [Nest] 6  - 12/30/2023, 9:05:37 PM    WARN [Error: File not found - /usr/src/app/upload/upload/898fa47d-ff65-4b82-978b-ac59e0560b42/f1926aac-fa61-4908-a3bf-4aaa27c62388.JPG.xmp
Dec 30 22:05:37 plonkie docker-immich_microservices-start[1341286]:     at ReadTask.parser (/usr/src/app/node_modules/exiftool-vendored/dist/ExifToolTask.js:43:29)
Dec 30 22:05:37 plonkie docker-immich_microservices-start[1341286]:     at ReadTask._Task_resolve (/usr/src/app/node_modules/batch-cluster/dist/Task.js:146:40)] Error reading exif data (upload/upload/898fa47d-ff65-4b82-978b-ac59e0560b42/f1926aac-fa61-4908-a3bf-4aaa27c62388.JPG.xmp): Error: File not found - /usr/src/app/upload/upload/898fa47d-ff65-4b82-978b-ac59e0560b42/f1926aac-fa61-4908-a3bf-4aaa27c62388.JPG.xmp
```

as well as:
```
Dec 30 22:05:37 plonkie docker-immich_microservices-start[1341286]: [Nest] 6  - 12/30/2023, 9:05:37 PM    WARN [MetadataService] Exif data has latitude and longitude of 0, setting to null
```

which may be related? The full `immich-go` command I am using is:

```
.\immich-go.exe -server https://i.amorgan.xyz -key [redacted] -no-colors-log -log-file=takeout-upload-log upload -google-photos .\takeout-*.zip
immich-go  0.9.6, commit 1782249564abb77f01780282ca4d8ddaf7ef6f69, built at 2023-12-30T08:30:25Z
```

The same occurs with the `-skip-verify-ssl` flag. This is on Windows 11 x86_64 using the v0.9.6 release exe.

**Comment by simulot** [comment]
Thanks for your report.

##  remote error: tls: bad record MAC

I can't really tell what this means.Immich go uses the very standard library provided by the go language, with default settings.

A google search https://www.google.com/search?q=golang++remote+error%3A+tls%3A+bad+record+MAC give some information:

https://github.com/googleapis/google-cloud-go/issues/1581#issuecomment-531817165

> bad record MAC is a very internal error, which usually means network corruption of some sorts (like a proxy changing the contents of the TCP stream), or a severe issue in the TLS stack.
> 
> The most useful thing for debugging the latter would be an issue on golang.org/issues with a PCAP and the result of setting tls.Config.KeyLogWriter during that network capture.

Other kind of responses:
- TLS packets tempered by a network appliance
- A network card having a problem
- A faulty network card driver. Often recoverable by turning off hardware preload features.
- Anti-virus software intercepting outgoing SSL packets
- Network MTU misconfiguration

I would suggest to change some conditions to learn more on the source of the problem
- use another connection,
- another client machine, another OS?
- bypass the network by running immich-go locally on the server.
- bypass immich-go by dropping files on the web app or using the official CLI

## xmp error

```
Error reading exif data (...): Error: File not found - .....JPG.xmp
```
the file isn't found... maybe because of the network error

**Comment by anoadragon453** [comment]
Thank you for your in-depth research! I'll give those alternative suggestions a go.

Otherwise, do you think it may be worth adding retries for failed uploads, in case of temporary network failure or other unexpected condition? Even something like max 3 retries per file would probably cover whatever issue I'm having. And it would help add general resilience to the upload process.

**Comment by simulot** [comment]
> Otherwise, do you think it may be worth adding retries for failed uploads, in case of temporary network failure or other unexpected condition? Even something like max 3 retries per file would probably cover whatever issue I'm having. And it would help add general resilience to the upload process.

Sure, added to the todo list

**Comment by BirgerK** [comment]
I had this problem using a traefik v3 as Reverse-Proxy. 

It’s gone since configuring the minimum TLS-Version from 1.2 to 1.3.

It’s probably not an issue of Immich-go, but a retry-mechanism would introduce more resilience on temporary network issues.
