### ISSUE TITLE
immich-go crashes while importing a Google Takeout export

### ISSUE THREAD

**Issue by DGTWT** [simulot/immich-go#364]
Hello, I am getting this error while trying to import a folder with Google Takeout files:

```
goroutine 25 [running]:
github.com/simulot/immich-go/browser/gp.(*Takeout).passTwo(0xc0000580a0, {0x9a6dc8, 0xc0000580f0}, {0xc003c26410, 0x25}, 0xc006d084e0)
        github.com/simulot/immich-go/browser/gp/googlephotos.go:486 +0x970
github.com/simulot/immich-go/browser/gp.(*Takeout).Browse.func1()
        github.com/simulot/immich-go/browser/gp/googlephotos.go:429 +0x12e
created by github.com/simulot/immich-go/browser/gp.(*Takeout).Browse in goroutine 12
        github.com/simulot/immich-go/browser/gp/googlephotos.go:425 +0xc6
```

immich-go can successfully upload about 600 GB of this ~750 GB takeout export until it suddenly gives this error. There is no additional info in the log files.

I am getting this error both in Windows (local) and Linux (in same LAN) computers while running this command:

- Windows (computer where immich is hosted):
./immich-go -server=http://localhost:2283 -key=XXX upload
-google-photos ./takeout/takeout-*.zip

- Linux (laptop in the same LAN):
./immich-go -no-ui -server=http://192.168.0.5:2283 -key=XXX -log-file ./log.txt upload
-google-photos ./takeout/takeout-*.zip

Any help would be highly appreciated :)

Thank you!
David

**Comment by DGTWT** [comment]
Additional info:

I copied the error message from the Linux machine, as I was running the Windows machine with the UI enabled and the message was almost unreadable. I will run the command again under Windows an provide the error message it outputs.

Used versions are 0.19.1 in both cases.

**Comment by DGTWT** [comment]
Windows error message:
```
./immich-go -no-ui -server=http://localhost:2283/ -key=XXX upload
-google-photos ./takeout/takeout-*.zip
```

```
Immich read 100%, Google Photos Analysis: 87%, Upload errors: 0, Uploaded 6% .panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x515370]

goroutine 40 [running]:
github.com/simulot/immich-go/browser/gp.(*Takeout).passTwo(0xc0000580a0, {0x6c6dc8, 0xc000058140}, {0xc005889780, 0x18}, 0xc00a5ee060)
        github.com/simulot/immich-go/browser/gp/googlephotos.go:486 +0x970
github.com/simulot/immich-go/browser/gp.(*Takeout).Browse.func1()
        github.com/simulot/immich-go/browser/gp/googlephotos.go:429 +0x12e
created by github.com/simulot/immich-go/browser/gp.(*Takeout).Browse in goroutine 36
        github.com/simulot/immich-go/browser/gp/googlephotos.go:425 +0xc6
```

**Comment by simulot** [comment]
oops! the program died before having a chance to write the log.

The program line that has triggered the error suggest that an image file can't be accessed, and this error isn't well handled. That could explain the panic message. I'll fix that today if possible. 

Anyway, the source of photos is a ZIP. Could you check the file integrity?

You can contact me on discord @simulot.

**Comment by DGTWT** [comment]
> oops! the program died before having a chance to write the log.
> 
> The program line that has triggered the error suggest that an image file can't be accessed, and this error isn't well handled. That could explain the panic message. I'll fix that today if possible.
> 
> Anyway, the source of photos is a ZIP. Could you check the file integrity?
> 
> You can contact me on discord @simulot.

I've tested the files with 7-zip and this may be the cause:

![image](https://github.com/simulot/immich-go/assets/21016677/4af6d41e-865c-4682-a6c5-0de3eb845ee5)

I will try removing these files and let you know, thanks!

**Comment by simulot** [comment]
You can't remove that file... All parts are linked... and you will have "missing JSON" errors.
May be you can just re-download it from the google takeout email

I'll improve the error management here. No urgency

**Comment by DGTWT** [comment]
> You can't remove that file... All parts are linked... and you will have "missing JSON" errors. May be you can just re-download it from the google takeout email
> 
> I'll improve the error management here. No urgency

I meant the files **inside** the zips :) 

I think it worked!

```
PS D:\> .\immich-go.exe -server=http://localhost:2283 -key=Jyr0a7DraIWFMOpCrWDYJHf4XKfj1pv3eOHtKVY -log-file ./logg.txt  upload -google-photos .\takeout\takeout-*.zip
immich-go  0.19.1, commit 3b8fc3d44cdfb029bcba83befd8b6fbf4347c8de, built at 2024-07-07T19:53:26Z
. _ _  _ _ . _|_     _  _
|| | || | ||(_| | ─ (_|(_)
            v 0.19.1 _)


Input analysis:
---------------
scanned image file                      :   36346
scanned video file                      :    6089
scanned sidecar file                    :   43546
discarded file                          :       2
unsupported file                        :      22
file duplicated in the input            :    7196
associated metadata file                :   37287
missing associated metadata file        :       0

Uploading:
----------
uploaded                                :       1
upload error                            :       0
file not selected                       :       0
server's asset upgraded with the input  :       0
server has same asset                   :   29575
server has a better asset               :      13

Check the log file:  ./logg.txt
```

Also the last lines of the log:

```
...
INFO | file duplicated in the input | file="Takeout/Google Fotos/Fotos destacadas de xxx(1)/PXL_20230228_072042835.PORTRAIT.jpg" title=PXL_20230228_072042835.PORTRAIT.jpg time="2024-07-11T11:07.55 CEST"
 INFO | 
Input analysis:
---------------
scanned image file                      :   36346
scanned video file                      :    6089
scanned sidecar file                    :   43546
discarded file                          :       2
unsupported file                        :      22
file duplicated in the input            :    7196
associated metadata file                :   37287
missing associated metadata file        :       0

Uploading:
----------
uploaded                                :       1
upload error                            :       0
file not selected                       :       0
server's asset upgraded with the input  :       0
server has same asset                   :   29575
server has a better asset               :      13
 | time="2024-07-11T11:08.10 CEST"

```
Though the reported usage for my account on the server says 550 GB and the zip files sum up to 750 GB :/

**Comment by simulot** [comment]
Duplicates are discarded by immich-go, and if not, by immich... no worries.

**Comment by DGTWT** [comment]
Ok, thank you so much! You've done an awesome work :)
