### ISSUE TITLE
Uploaded Videos missing from "Explore -> categories - Videos",  otherwise good in Places, Metadata seems intact

### ISSUE THREAD

**Issue by Deathproof76** [simulot/immich-go#6]
There wasn't any error message as far as I can tell, maybe it's related to https://github.com/simulot/immich-go/issues/3 or maybe it's a bug with immich itself. 

But I noticed that uploaded videos, when you look in explore -> categories - videos are simply not there. I reran every conceivable job from the admin panel. But I can only find the ones under the video category that I uploaded via webui or via phone.

They seem to be okay in places or the timeline, metadata like gps coordinates is there. First I thought that there was some Google Pixel 6 madness involved, but older videos from other phones are missing too.

**Comment by simulot** [comment]
I have the same camera as you. I haven't noticed this problem.
Was you able to determine the type of files concerned by the problem?

May be you can extract one from the takeout archive and run the file command?
```sh
file PXL_20230703_183645724.TS.mp4 
PXL_20230703_183645724.TS.mp4: ISO Media, MP4 Base Media v1 [ISO 14496-12:2003]
```

**Comment by Deathproof76** [comment]
```
file 20210722_194934.mp4
20210722_194934.mp4: ISO Media, MP4 v2 [ISO 14496-14]
```
I also tried uploading the extracted bare file via webui, get's skipped because of duplicate, also not visible in explore - videos.

Mmmmm..... okay, I'm sure now that it's actually a problem with either ffprobe, immich, the way gphotos handles files or my docker config for immich. I needed to modify ffmpeg and some permissions to get hardware transcoding to work with my 13th gen Intel UHD770.  https://github.com/immich-app/immich/issues/3585 https://github.com/immich-app/immich/issues/3585#issuecomment-1689261413 https://github.com/imagegenius/docker-immich/issues/152

 I'm seeing these errors in the immich log when doing sidecare metadata:
```
[Nest] 1560  - 08/25/2023, 10:58:27 AM   ERROR [JobService] Error: ffprobe exited with code 1
ffprobe version 6.0-Jellyfin Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12 (Ubuntu 12.3.0-1ubuntu1~23.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55ca1e907fc0] moov atom not found
/photos/library/admin/2019/February-12/1_2019-02-12_14-37-04.mp4: Invalid data found when processing input
    at ChildProcess.<anonymous> (/app/immich/server/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Nest] 1560  - 08/25/2023, 10:58:27 AM   ERROR [JobService] Object:
{
  "id": "b534673b-6cb9-44b8-855b-6784bc78ad76"
}
[Nest] 1560  - 08/25/2023, 10:58:27 AM   ERROR [JobService] Unable to run job handler: Error: ffprobe exited with code 1
ffprobe version 6.0-Jellyfin Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12 (Ubuntu 12.3.0-1ubuntu1~23.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55752e0f5fc0] moov atom not found
/photos/upload/4d2fd6f2-0050-466d-ba32-c0b77244ac65/a3265d7b-e361-4ad3-a78c-a7ab8b5a56fc.mp4: Invalid data found when processing input
[Nest] 1560  - 08/25/2023, 10:58:27 AM   ERROR [JobService] Error: ffprobe exited with code 1
ffprobe version 6.0-Jellyfin Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12 (Ubuntu 12.3.0-1ubuntu1~23.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55752e0f5fc0] moov atom not found
/photos/upload/4d2fd6f2-0050-466d-ba32-c0b77244ac65/a3265d7b-e361-4ad3-a78c-a7ab8b5a56fc.mp4: Invalid data found when processing input
    at ChildProcess.<anonymous> (/app/immich/server/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Nest] 1560  - 08/25/2023, 10:58:27 AM   ERROR [JobService] Object:
{
  "id": "2ae59ad2-0965-4f53-91d8-31e9162e6ff5"
}
```

So yeah, the videos are playable in immich and the preview also get's encoded. Just ffprobe has problems. sorry about the ruckus😅

**Comment by simulot** [comment]
No problem.

**Comment by Deathproof76** [comment]
Just fyi and for posterity: I found out so far that the ffprobe error is only related to certain files that seem to have been corrupted and really can't be played.  Even though the extraction process of the Takeout.zip throws no errors and the files are playable when downloaded directly from google photos.

Chatgpt helped me write a python script to identify affected files via ffprobe, i uploaded it to gists
https://gist.github.com/Deathproof76/fdc283c77d9e4f1d532bfe71314df0d2

The weird thing is that even though only about 30 files are affected, the other intact files are still not shown in Explore -> categories - Videos. It seems likely that when doing sidecar metadata in immich it checks via ffprobe chronologically and stops the job after a certain amount of errors. That would explain why there is this hard cutoff where only videos after 2022 are shown in categories - Videos. 🤷‍♂️

**Comment by simulot** [comment]
I would like to confirm that the files aren't corrupted in anyway by the immich-go program.
Have you checked with files from the takeout zip, or those stored with Immich?
